% script VARIABLES_TRAVELLERS
INDEX_LOMBARDIA =1;
INDEX_LAZIO     =2;
INDEX_CAMPANIA  =3;

LEGEND_PLOT     =1;
THREE_PLOT      =2;
DEATHS_PLOT     =3;
CHEATERS_PLOT   =4;

NULL_MODEL      =0;
STANDARD_RMS    =1;
ROOT_NULL_MODEL =2;

BEST_JUMPERS.REGIONS{INDEX_LOMBARDIA}=0;
BEST_JUMPERS.REGIONS{INDEX_LAZIO}    =36;
BEST_JUMPERS.REGIONS{INDEX_CAMPANIA} =37;

SAVE_DIR='FIGURES/';